/* Generated By:JavaCC: Do not edit this line. IndicatorParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface IndicatorParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CONSTANT = 2;
  /** RegularExpression Id. */
  int INDICATOR = 3;
  /** RegularExpression Id. */
  int CALCULATION = 4;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "<CONSTANT>",
    "<INDICATOR>",
    "<CALCULATION>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
  };

}
