/* Generated By:JavaCC: Do not edit this line. IndicatorParserConstants.java */
package modelo.indicator.parser;

/**
 * Token literal values and constants. Generated by
 * org.javacc.parser.OtherFilesGen#start()
 */
public interface IndicatorParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CONSTANT = 2;
  /** RegularExpression Id. */
  int IDENTIFIER = 3;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = { "<EOF>", "\" \"", "<CONSTANT>", "<IDENTIFIER>", "\"+\"", "\"-\"", "\"*\"", "\"/\"", "\"(\"",
      "\")\"", "\"@\"", "\"#\"", };

}
